### ISSUE TITLE
没有区分master和node节点？

### ISSUE THREAD

**Issue by kala888** [EagleChen/kubernetes_init#1]
FYI？

**Comment by EagleChen** [comment]
这个项目主要是为了解决国内网络环境相关的问题（并且加速安装）， 步骤跟官方的是一样的， 所以并没有写上安装 node 节点的脚本。

如果要安装 node 节点， 不运行 `kubeadm init` 而是运行 `kubeadm join ... ` 命令即可。
其他组件， 如docker， kube* 等， 与master上的安装方式一致。

当然， 我以后可以考虑把安装 node 的函数写上。

**Comment by EagleChen** [comment]
@kala888 

43811ae73ed636c4879a439bd69705b33778e9eb 新加的commit， 区分了master和node

**Comment by kala888** [comment]
@EagleChen 666参考价值很高
